# conda env create -f environment.yml
name: vlm-shap
channels:
  - pytorch
  - huggingface
  - nvidia
  - anaconda
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - accelerate
  - aiohttp
  - aiosignal
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - bitsandbytes
  - c-ares
  - cmake
  - colorama
  - cuda-cccl
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-cudart
  - datasets
  - dill
  - einops
  - ffmpeg
  - flash-attn
  - fontconfig
  - frozenlist
  - fsspec
  - gflags
  - glog
  - huggingface_hub
  - icu
  - iniconfig
  - keyutils
  - libabseil
  - libarrow
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcublas
  - libcufft
  - libcurand
  - libcusolver
  - libcusparse
  - libev
  - libevent
  - libexpat
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - liblapack
  - libllvm14
  - libllvm15
  - libllvm16
  - libnghttp2
  - libnl
  - libnpp
  - libnsl
  - libnuma
  - libnvjitlink
  - libnvjpeg
  - libparquet
  - libprotobuf
  - libsentencepiece
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libthrift
  - libutf8proc
  - libuuid
  - libxcrypt
  - libxkbcommon
  - libxml2
  - llvmlite
  - matplotlib
  - multidict
  - multiprocess
  - ninja
  - nsight-compute
  - numba
  - ocl-icd
  - openssl
  - orc
  - packaging
  - pandas
  - pluggy
  - protobuf
  - psutil
  - pyarrow
  - pytest
  - python-dateutil
  - python-tzdata
  - python-xxhash
  - pytorch-mutex
  - pytz
  - rdma-core
  - re2
  - regex
  - s2n
  - safetensors
  - scipy
  - sentencepiece
  - six
  - tk
  - tokenizers
  - tqdm
  - transformers
  - triton
  - ucx
  - wheel
  - xkeyboard-config
  - xorg-kbproto
  - xorg-libx11
  - xorg-libxau
  - xorg-xextproto
  - xxhash
  - yarl
  - zlib
  - pip:
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - nvidia-nvtx-cu12
    - lion-pytorch
    - libre2
    - en-core-web-sm
    - torch